### ISSUE TITLE
Command line options are out of date

### ISSUE THREAD

**Issue by Susurrus** [xela144/CANaconda#45]
Maybe it's just the `--help` docs, but for example `--messages` should probably `--metadata`, since that's what the files are called now. Additionally, `--nogui` takes a PORT argument, which seems redundant with the `-p` option.

**Comment by xela144** [comment]
104f318dcbc9b7855ff775fd5f91fc57c008dd39

**Comment by xela144** [comment]
--nogui has a positional argument, port, which is necessary since there is no other way to get the port.

Without --nogui, we launch the GUI. --port is a shortcut for launching the program with a port pre-selected. 

I can re-order this logic to make it more clear.

**Comment by Susurrus** [comment]
Make the --nogui option just a boolean flag and leave the port argument as it is. It should be required when nogui is specified otherwise optional. This is a nicer design.

**Comment by xela144** [comment]
afd22327adde3689bf5904511ba9f2867e8e7894
