### ISSUE TITLE
Add a README.txt file for metadata

### ISSUE THREAD

**Issue by Susurrus** [xela144/CANaconda#76]
The `metadata/` folder should have a README describing the XML file format. Ideally there'd be a proper .dtd file, but that can wait for now.

**Comment by Susurrus** [comment]
This should be much more expansive than the XML format specs in the main README.txt, for example it should list the possible field types (currently int, bitfield, and boolean).

**Comment by xela144** [comment]
Have a look... and feel free to re-open.

**Comment by xela144** [comment]
[link to metadata folder](https://github.com/xela144/CANaconda/tree/master/metadata)

**Comment by Susurrus** [comment]
Looks good. Also see my commit bb07a14bcf.
