### ISSUE TITLE
Right-clicking on the main menubar brings up menu with single checkbox

### ISSUE THREAD

**Issue by Susurrus** [xela144/CANaconda#82]
Unchecking it removes the things below the menubar. Very odd. Probably a single setting somewhere that should be removed.

**Comment by xela144** [comment]
Yes... curious because I've noticed that for a while but have never figured out what it is.

**Comment by Susurrus** [comment]
Pretty certain it's a QToolBar. Just remove it from the .ui file.

**Comment by xela144** [comment]
Yaaaay!!!
